apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
  namespace: stage
  labels:
    app: cache-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      containers:
        - name: cache-service
          image: registry.24cases.ru/stardrop1/cache-service:${IMAGE_TAG}
          ports:
            - containerPort: 7006
          envFrom:
            - secretRef:
                name: common-env-secret
      imagePullSecrets:
        - name: gitlab-regcred
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: stage
spec:
  selector:
    app: cache-service
  ports:
    - protocol: TCP
      port: 7006
      targetPort: 7006
  type: ClusterIP